# Generated by Django 4.2.6 on 2023-10-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=100)),
                ('date_of_registration', models.DateField()),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_address', models.CharField(max_length=200)),
                ('buyer_number', models.CharField(max_length=20)),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_address', models.CharField(max_length=200)),
                ('seller_number', models.CharField(max_length=20)),
                ('ward_patwari_halka', models.CharField(max_length=100)),
                ('ward_patwari_halka_name', models.CharField(max_length=100)),
                ('property_address', models.CharField(max_length=200)),
                ('plot_number', models.CharField(max_length=50)),
                ('north', models.CharField(max_length=50)),
                ('south', models.CharField(max_length=50)),
                ('east', models.CharField(max_length=50)),
                ('west', models.CharField(max_length=50)),
            ],
        ),
    ]
