# Generated by Django 4.2.6 on 2023-10-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_captcha', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('district_registered', models.CharField(max_length=255, verbose_name='District (Where Document Was Registered)')),
                ('district_search', models.CharField(max_length=255, verbose_name='District Being Used for Search')),
                ('search_registered_sampada', models.BooleanField(default=False)),
                ('financial_year', models.CharField(max_length=10, verbose_name='Financial Year')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('tehsil', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_area', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_area_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ward_number_patwari_number', models.CharField(blank=True, max_length=255, null=True)),
                ('mohalla_colony_name_society_road', models.CharField(blank=True, max_length=255, null=True)),
                ('khasra_number', models.CharField(blank=True, max_length=255, null=True)),
                ('transacting_party_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transacting Party First Name')),
                ('transacting_party_middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transacting Party Middle Name')),
                ('transacting_party_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transacting Party Last Name')),
                ('transacting_party_mother_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transacting Party Mother Name')),
                ('transacting_party_father_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transacting Party Father Name')),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Organization Name')),
            ],
        ),
    ]
